apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: virtool-job-iimi
spec:
  jobTargetRef:
    backoffLimit: 1
    completions: 1
    parallelism: 1
    ttlSecondsAfterFinished: 300
    template:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        labels:
          app: job-iimi
      spec:
        containers:
          - name: job-iimi
            image: ghcr.io/virtool/iimi:0.1.0
            imagePullPolicy: Always
            args: [run-workflow]
            envFrom:
              - configMapRef:
                  name: virtool-jobs-config
            env:
              - name: VT_PROC
                value: "4"
              - name: VT_MEM
                value: "10"
              - name: VT_REDIS_LIST_NAME
                value: "jobs_iimi"
            resources:
              limits:
                cpu: "5"
                memory: 11Gi
              requests:
                cpu: "5"
                memory: 11Gi
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 1
  triggers:
    - type: redis
      metadata:
        addressFromEnv: VT_REDIS_HOST
        passwordFromEnv: VT_REDIS_PASSWORD
        listName: jobs_iimi
        listLength: "1"
